# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/default.xdc

# XDC: imports/xdc/zc702.xdc

# XDC: imports/xdc/pl_zc702.xdc

# Block Designs: bd/project_1/project_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1 || ORIG_REF_NAME==project_1} -quiet] -quiet

# IP: bd/project_1/ip/project_1_zynqps_0_0/project_1_zynqps_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_zynqps_0_0 || ORIG_REF_NAME==project_1_zynqps_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_gpio_0_0/project_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_axi_gpio_0_0 || ORIG_REF_NAME==project_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_proc_sys_reset_0_0/project_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_proc_sys_reset_0_0 || ORIG_REF_NAME==project_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_smartcon_0_0/project_1_smartcon_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_smartcon_0_0 || ORIG_REF_NAME==project_1_smartcon_0_0} -quiet] -quiet

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/project_1_ooc.xdc
