# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_smartcon_0_0/project_1_smartcon_0_0.xci
# IP: The module: 'project_1_smartcon_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/bd_4acd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_0/bd_4acd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_1/bd_4acd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_2/bd_4acd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_3/bd_4acd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_4/bd_4acd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_5/bd_4acd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_6/bd_4acd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_7/bd_4acd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_8/bd_4acd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_9/bd_4acd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_10/bd_4acd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_11/bd_4acd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_12/bd_4acd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_1/bd_4acd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_1/bd_4acd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_5/bd_4acd_s00a2s_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_6/bd_4acd_sarn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_7/bd_4acd_srn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_8/bd_4acd_sawn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_9/bd_4acd_swn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_10/bd_4acd_sbn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_11/bd_4acd_m00s2a_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_smartcon_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_smartcon_0_0/project_1_smartcon_0_0.xci
# IP: The module: 'project_1_smartcon_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/bd_4acd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_0/bd_4acd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_1/bd_4acd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_2/bd_4acd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_3/bd_4acd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_4/bd_4acd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_5/bd_4acd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_6/bd_4acd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_7/bd_4acd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_8/bd_4acd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_9/bd_4acd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_10/bd_4acd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_11/bd_4acd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_12/bd_4acd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_1/bd_4acd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_1/bd_4acd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_5/bd_4acd_s00a2s_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_6/bd_4acd_sarn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_7/bd_4acd_srn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_8/bd_4acd_sawn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_9/bd_4acd_swn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_10/bd_4acd_sbn_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/bd_0/ip/ip_11/bd_4acd_m00s2a_0_ooc.xdc

# XDC: /tmp/tmp.mpnEjmitRV/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_smartcon_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_smartcon_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
